/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FlyerRouteImport } from './routes/flyer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeIndexRouteImport } from './routes/home.index'
import { Route as OrderSuccessRouteImport } from './routes/order.success'
import { Route as OrderCancelledRouteImport } from './routes/order.cancelled'
import { Route as OfferTokenRouteImport } from './routes/offer.$token'
import { Route as OSlugRouteImport } from './routes/o.$slug'
import { Route as HomeSignupRouteImport } from './routes/home.signup'
import { Route as HomeLoginRouteImport } from './routes/home.login'
import { Route as AuthenticatedSessionsRouteImport } from './routes/_authenticated/sessions'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedFrequenciesRouteImport } from './routes/_authenticated/frequencies'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedAvailabilityRouteImport } from './routes/_authenticated/availability'
import { Route as AuthenticatedAudioRouteImport } from './routes/_authenticated/audio'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSessionsIndexRouteImport } from './routes/_authenticated/sessions.index'
import { Route as AuthenticatedBookingsIndexRouteImport } from './routes/_authenticated/bookings.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as LovableEmailEventsRouteImport } from './routes/lovable/email/events'
import { Route as AuthenticatedSessionsNewRouteImport } from './routes/_authenticated/sessions.new'
import { Route as AuthenticatedBookingsIdRouteImport } from './routes/_authenticated/bookings.$id'
import { Route as AuthenticatedAdminTeamRouteImport } from './routes/_authenticated/admin.team'
import { Route as AuthenticatedAdminShippingRouteImport } from './routes/_authenticated/admin.shipping'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin.services'
import { Route as AuthenticatedAdminSalesRouteImport } from './routes/_authenticated/admin.sales'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminPromoCodesRouteImport } from './routes/_authenticated/admin.promo-codes'
import { Route as AuthenticatedAdminPolicyTemplatesRouteImport } from './routes/_authenticated/admin.policy-templates'
import { Route as AuthenticatedAdminPlatformAdminsRouteImport } from './routes/_authenticated/admin.platform-admins'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminOrganisationsRouteImport } from './routes/_authenticated/admin.organisations'
import { Route as AuthenticatedAdminOnboardingRouteImport } from './routes/_authenticated/admin.onboarding'
import { Route as AuthenticatedAdminMetricsRouteImport } from './routes/_authenticated/admin.metrics'
import { Route as AuthenticatedAdminMarketingRouteImport } from './routes/_authenticated/admin.marketing'
import { Route as AuthenticatedAdminInvoicesRouteImport } from './routes/_authenticated/admin.invoices'
import { Route as AuthenticatedAdminGlobalServicesRouteImport } from './routes/_authenticated/admin.global-services'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin.clients'
import { Route as AuthenticatedAdminAccessCodesRouteImport } from './routes/_authenticated/admin.access-codes'
import { Route as AuthenticatedSessionsIdIndexRouteImport } from './routes/_authenticated/sessions.$id.index'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksStripeRouteImport } from './routes/api/public/hooks/stripe'
import { Route as ApiPublicHooksOfferTickRouteImport } from './routes/api/public/hooks/offer-tick'
import { Route as AuthenticatedSessionsIdPlayRouteImport } from './routes/_authenticated/sessions.$id.play'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FlyerRoute = FlyerRouteImport.update({
  id: '/flyer',
  path: '/flyer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order/success',
  path: '/order/success',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderCancelledRoute = OrderCancelledRouteImport.update({
  id: '/order/cancelled',
  path: '/order/cancelled',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferTokenRoute = OfferTokenRouteImport.update({
  id: '/offer/$token',
  path: '/offer/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OSlugRoute = OSlugRouteImport.update({
  id: '/o/$slug',
  path: '/o/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeSignupRoute = HomeSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => HomeRoute,
} as any)
const HomeLoginRoute = HomeLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => HomeRoute,
} as any)
const AuthenticatedSessionsRoute = AuthenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFrequenciesRoute =
  AuthenticatedFrequenciesRouteImport.update({
    id: '/frequencies',
    path: '/frequencies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAvailabilityRoute =
  AuthenticatedAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAudioRoute = AuthenticatedAudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionsIndexRoute =
  AuthenticatedSessionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSessionsRoute,
  } as any)
const AuthenticatedBookingsIndexRoute =
  AuthenticatedBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const LovableEmailEventsRoute = LovableEmailEventsRouteImport.update({
  id: '/lovable/email/events',
  path: '/lovable/email/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSessionsNewRoute =
  AuthenticatedSessionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSessionsRoute,
  } as any)
const AuthenticatedBookingsIdRoute = AuthenticatedBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminTeamRoute = AuthenticatedAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminShippingRoute =
  AuthenticatedAdminShippingRouteImport.update({
    id: '/shipping',
    path: '/shipping',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSalesRoute = AuthenticatedAdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPromoCodesRoute =
  AuthenticatedAdminPromoCodesRouteImport.update({
    id: '/promo-codes',
    path: '/promo-codes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPolicyTemplatesRoute =
  AuthenticatedAdminPolicyTemplatesRouteImport.update({
    id: '/policy-templates',
    path: '/policy-templates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlatformAdminsRoute =
  AuthenticatedAdminPlatformAdminsRouteImport.update({
    id: '/platform-admins',
    path: '/platform-admins',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrganisationsRoute =
  AuthenticatedAdminOrganisationsRouteImport.update({
    id: '/organisations',
    path: '/organisations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOnboardingRoute =
  AuthenticatedAdminOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMetricsRoute =
  AuthenticatedAdminMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketingRoute =
  AuthenticatedAdminMarketingRouteImport.update({
    id: '/marketing',
    path: '/marketing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInvoicesRoute =
  AuthenticatedAdminInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGlobalServicesRoute =
  AuthenticatedAdminGlobalServicesRouteImport.update({
    id: '/global-services',
    path: '/global-services',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAccessCodesRoute =
  AuthenticatedAdminAccessCodesRouteImport.update({
    id: '/access-codes',
    path: '/access-codes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedSessionsIdIndexRoute =
  AuthenticatedSessionsIdIndexRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => AuthenticatedSessionsRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksStripeRoute = ApiPublicHooksStripeRouteImport.update({
  id: '/api/public/hooks/stripe',
  path: '/api/public/hooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksOfferTickRoute = ApiPublicHooksOfferTickRouteImport.update({
  id: '/api/public/hooks/offer-tick',
  path: '/api/public/hooks/offer-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSessionsIdPlayRoute =
  AuthenticatedSessionsIdPlayRouteImport.update({
    id: '/$id/play',
    path: '/$id/play',
    getParentRoute: () => AuthenticatedSessionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/flyer': typeof FlyerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/audio': typeof AuthenticatedAudioRoute
  '/availability': typeof AuthenticatedAvailabilityRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/frequencies': typeof AuthenticatedFrequenciesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/services': typeof AuthenticatedServicesRoute
  '/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/home/login': typeof HomeLoginRoute
  '/home/signup': typeof HomeSignupRoute
  '/o/$slug': typeof OSlugRoute
  '/offer/$token': typeof OfferTokenRoute
  '/order/cancelled': typeof OrderCancelledRoute
  '/order/success': typeof OrderSuccessRoute
  '/home/': typeof HomeIndexRoute
  '/admin/access-codes': typeof AuthenticatedAdminAccessCodesRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/global-services': typeof AuthenticatedAdminGlobalServicesRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/marketing': typeof AuthenticatedAdminMarketingRoute
  '/admin/metrics': typeof AuthenticatedAdminMetricsRoute
  '/admin/onboarding': typeof AuthenticatedAdminOnboardingRoute
  '/admin/organisations': typeof AuthenticatedAdminOrganisationsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/platform-admins': typeof AuthenticatedAdminPlatformAdminsRoute
  '/admin/policy-templates': typeof AuthenticatedAdminPolicyTemplatesRoute
  '/admin/promo-codes': typeof AuthenticatedAdminPromoCodesRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/sales': typeof AuthenticatedAdminSalesRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/shipping': typeof AuthenticatedAdminShippingRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/sessions/new': typeof AuthenticatedSessionsNewRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/sessions/': typeof AuthenticatedSessionsIndexRoute
  '/sessions/$id/play': typeof AuthenticatedSessionsIdPlayRoute
  '/api/public/hooks/offer-tick': typeof ApiPublicHooksOfferTickRoute
  '/api/public/hooks/stripe': typeof ApiPublicHooksStripeRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/sessions/$id/': typeof AuthenticatedSessionsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/flyer': typeof FlyerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/audio': typeof AuthenticatedAudioRoute
  '/availability': typeof AuthenticatedAvailabilityRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/frequencies': typeof AuthenticatedFrequenciesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/services': typeof AuthenticatedServicesRoute
  '/home/login': typeof HomeLoginRoute
  '/home/signup': typeof HomeSignupRoute
  '/o/$slug': typeof OSlugRoute
  '/offer/$token': typeof OfferTokenRoute
  '/order/cancelled': typeof OrderCancelledRoute
  '/order/success': typeof OrderSuccessRoute
  '/home': typeof HomeIndexRoute
  '/admin/access-codes': typeof AuthenticatedAdminAccessCodesRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/global-services': typeof AuthenticatedAdminGlobalServicesRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/marketing': typeof AuthenticatedAdminMarketingRoute
  '/admin/metrics': typeof AuthenticatedAdminMetricsRoute
  '/admin/onboarding': typeof AuthenticatedAdminOnboardingRoute
  '/admin/organisations': typeof AuthenticatedAdminOrganisationsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/platform-admins': typeof AuthenticatedAdminPlatformAdminsRoute
  '/admin/policy-templates': typeof AuthenticatedAdminPolicyTemplatesRoute
  '/admin/promo-codes': typeof AuthenticatedAdminPromoCodesRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/sales': typeof AuthenticatedAdminSalesRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/shipping': typeof AuthenticatedAdminShippingRoute
  '/admin/team': typeof AuthenticatedAdminTeamRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/sessions/new': typeof AuthenticatedSessionsNewRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/bookings': typeof AuthenticatedBookingsIndexRoute
  '/sessions': typeof AuthenticatedSessionsIndexRoute
  '/sessions/$id/play': typeof AuthenticatedSessionsIdPlayRoute
  '/api/public/hooks/offer-tick': typeof ApiPublicHooksOfferTickRoute
  '/api/public/hooks/stripe': typeof ApiPublicHooksStripeRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/sessions/$id': typeof AuthenticatedSessionsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/flyer': typeof FlyerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/audio': typeof AuthenticatedAudioRoute
  '/_authenticated/availability': typeof AuthenticatedAvailabilityRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/frequencies': typeof AuthenticatedFrequenciesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/_authenticated/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/home/login': typeof HomeLoginRoute
  '/home/signup': typeof HomeSignupRoute
  '/o/$slug': typeof OSlugRoute
  '/offer/$token': typeof OfferTokenRoute
  '/order/cancelled': typeof OrderCancelledRoute
  '/order/success': typeof OrderSuccessRoute
  '/home/': typeof HomeIndexRoute
  '/_authenticated/admin/access-codes': typeof AuthenticatedAdminAccessCodesRoute
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/_authenticated/admin/global-services': typeof AuthenticatedAdminGlobalServicesRoute
  '/_authenticated/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/_authenticated/admin/marketing': typeof AuthenticatedAdminMarketingRoute
  '/_authenticated/admin/metrics': typeof AuthenticatedAdminMetricsRoute
  '/_authenticated/admin/onboarding': typeof AuthenticatedAdminOnboardingRoute
  '/_authenticated/admin/organisations': typeof AuthenticatedAdminOrganisationsRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/platform-admins': typeof AuthenticatedAdminPlatformAdminsRoute
  '/_authenticated/admin/policy-templates': typeof AuthenticatedAdminPolicyTemplatesRoute
  '/_authenticated/admin/promo-codes': typeof AuthenticatedAdminPromoCodesRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/sales': typeof AuthenticatedAdminSalesRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/shipping': typeof AuthenticatedAdminShippingRoute
  '/_authenticated/admin/team': typeof AuthenticatedAdminTeamRoute
  '/_authenticated/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/_authenticated/sessions/new': typeof AuthenticatedSessionsNewRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/_authenticated/sessions/': typeof AuthenticatedSessionsIndexRoute
  '/_authenticated/sessions/$id/play': typeof AuthenticatedSessionsIdPlayRoute
  '/api/public/hooks/offer-tick': typeof ApiPublicHooksOfferTickRoute
  '/api/public/hooks/stripe': typeof ApiPublicHooksStripeRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_authenticated/sessions/$id/': typeof AuthenticatedSessionsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/flyer'
    | '/forgot-password'
    | '/home'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/audio'
    | '/availability'
    | '/change-password'
    | '/clients'
    | '/dashboard'
    | '/frequencies'
    | '/profile'
    | '/services'
    | '/sessions'
    | '/home/login'
    | '/home/signup'
    | '/o/$slug'
    | '/offer/$token'
    | '/order/cancelled'
    | '/order/success'
    | '/home/'
    | '/admin/access-codes'
    | '/admin/clients'
    | '/admin/global-services'
    | '/admin/invoices'
    | '/admin/marketing'
    | '/admin/metrics'
    | '/admin/onboarding'
    | '/admin/organisations'
    | '/admin/payments'
    | '/admin/platform-admins'
    | '/admin/policy-templates'
    | '/admin/promo-codes'
    | '/admin/reports'
    | '/admin/sales'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/team'
    | '/bookings/$id'
    | '/sessions/new'
    | '/lovable/email/events'
    | '/admin/'
    | '/bookings/'
    | '/sessions/'
    | '/sessions/$id/play'
    | '/api/public/hooks/offer-tick'
    | '/api/public/hooks/stripe'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/sessions/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/flyer'
    | '/forgot-password'
    | '/reset-password'
    | '/sitemap.xml'
    | '/audio'
    | '/availability'
    | '/change-password'
    | '/clients'
    | '/dashboard'
    | '/frequencies'
    | '/profile'
    | '/services'
    | '/home/login'
    | '/home/signup'
    | '/o/$slug'
    | '/offer/$token'
    | '/order/cancelled'
    | '/order/success'
    | '/home'
    | '/admin/access-codes'
    | '/admin/clients'
    | '/admin/global-services'
    | '/admin/invoices'
    | '/admin/marketing'
    | '/admin/metrics'
    | '/admin/onboarding'
    | '/admin/organisations'
    | '/admin/payments'
    | '/admin/platform-admins'
    | '/admin/policy-templates'
    | '/admin/promo-codes'
    | '/admin/reports'
    | '/admin/sales'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/shipping'
    | '/admin/team'
    | '/bookings/$id'
    | '/sessions/new'
    | '/lovable/email/events'
    | '/admin'
    | '/bookings'
    | '/sessions'
    | '/sessions/$id/play'
    | '/api/public/hooks/offer-tick'
    | '/api/public/hooks/stripe'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/sessions/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/flyer'
    | '/forgot-password'
    | '/home'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/audio'
    | '/_authenticated/availability'
    | '/_authenticated/change-password'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/frequencies'
    | '/_authenticated/profile'
    | '/_authenticated/services'
    | '/_authenticated/sessions'
    | '/home/login'
    | '/home/signup'
    | '/o/$slug'
    | '/offer/$token'
    | '/order/cancelled'
    | '/order/success'
    | '/home/'
    | '/_authenticated/admin/access-codes'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/global-services'
    | '/_authenticated/admin/invoices'
    | '/_authenticated/admin/marketing'
    | '/_authenticated/admin/metrics'
    | '/_authenticated/admin/onboarding'
    | '/_authenticated/admin/organisations'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/platform-admins'
    | '/_authenticated/admin/policy-templates'
    | '/_authenticated/admin/promo-codes'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/sales'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/shipping'
    | '/_authenticated/admin/team'
    | '/_authenticated/bookings/$id'
    | '/_authenticated/sessions/new'
    | '/lovable/email/events'
    | '/_authenticated/admin/'
    | '/_authenticated/bookings/'
    | '/_authenticated/sessions/'
    | '/_authenticated/sessions/$id/play'
    | '/api/public/hooks/offer-tick'
    | '/api/public/hooks/stripe'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/_authenticated/sessions/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FlyerRoute: typeof FlyerRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  OSlugRoute: typeof OSlugRoute
  OfferTokenRoute: typeof OfferTokenRoute
  OrderCancelledRoute: typeof OrderCancelledRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  LovableEmailEventsRoute: typeof LovableEmailEventsRoute
  ApiPublicHooksOfferTickRoute: typeof ApiPublicHooksOfferTickRoute
  ApiPublicHooksStripeRoute: typeof ApiPublicHooksStripeRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flyer': {
      id: '/flyer'
      path: '/flyer'
      fullPath: '/flyer'
      preLoaderRoute: typeof FlyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/order/success': {
      id: '/order/success'
      path: '/order/success'
      fullPath: '/order/success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/cancelled': {
      id: '/order/cancelled'
      path: '/order/cancelled'
      fullPath: '/order/cancelled'
      preLoaderRoute: typeof OrderCancelledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer/$token': {
      id: '/offer/$token'
      path: '/offer/$token'
      fullPath: '/offer/$token'
      preLoaderRoute: typeof OfferTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o/$slug': {
      id: '/o/$slug'
      path: '/o/$slug'
      fullPath: '/o/$slug'
      preLoaderRoute: typeof OSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/signup': {
      id: '/home/signup'
      path: '/signup'
      fullPath: '/home/signup'
      preLoaderRoute: typeof HomeSignupRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/login': {
      id: '/home/login'
      path: '/login'
      fullPath: '/home/login'
      preLoaderRoute: typeof HomeLoginRouteImport
      parentRoute: typeof HomeRoute
    }
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/frequencies': {
      id: '/_authenticated/frequencies'
      path: '/frequencies'
      fullPath: '/frequencies'
      preLoaderRoute: typeof AuthenticatedFrequenciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/availability': {
      id: '/_authenticated/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AuthenticatedAvailabilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audio': {
      id: '/_authenticated/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AuthenticatedAudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/': {
      id: '/_authenticated/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AuthenticatedSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedSessionsRoute
    }
    '/_authenticated/bookings/': {
      id: '/_authenticated/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AuthenticatedBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/events': {
      id: '/lovable/email/events'
      path: '/lovable/email/events'
      fullPath: '/lovable/email/events'
      preLoaderRoute: typeof LovableEmailEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sessions/new': {
      id: '/_authenticated/sessions/new'
      path: '/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof AuthenticatedSessionsNewRouteImport
      parentRoute: typeof AuthenticatedSessionsRoute
    }
    '/_authenticated/bookings/$id': {
      id: '/_authenticated/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof AuthenticatedBookingsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/team': {
      id: '/_authenticated/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AuthenticatedAdminTeamRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/shipping': {
      id: '/_authenticated/admin/shipping'
      path: '/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AuthenticatedAdminShippingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sales': {
      id: '/_authenticated/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AuthenticatedAdminSalesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/promo-codes': {
      id: '/_authenticated/admin/promo-codes'
      path: '/promo-codes'
      fullPath: '/admin/promo-codes'
      preLoaderRoute: typeof AuthenticatedAdminPromoCodesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/policy-templates': {
      id: '/_authenticated/admin/policy-templates'
      path: '/policy-templates'
      fullPath: '/admin/policy-templates'
      preLoaderRoute: typeof AuthenticatedAdminPolicyTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/platform-admins': {
      id: '/_authenticated/admin/platform-admins'
      path: '/platform-admins'
      fullPath: '/admin/platform-admins'
      preLoaderRoute: typeof AuthenticatedAdminPlatformAdminsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/organisations': {
      id: '/_authenticated/admin/organisations'
      path: '/organisations'
      fullPath: '/admin/organisations'
      preLoaderRoute: typeof AuthenticatedAdminOrganisationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/onboarding': {
      id: '/_authenticated/admin/onboarding'
      path: '/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AuthenticatedAdminOnboardingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/metrics': {
      id: '/_authenticated/admin/metrics'
      path: '/metrics'
      fullPath: '/admin/metrics'
      preLoaderRoute: typeof AuthenticatedAdminMetricsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/marketing': {
      id: '/_authenticated/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AuthenticatedAdminMarketingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invoices': {
      id: '/_authenticated/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/global-services': {
      id: '/_authenticated/admin/global-services'
      path: '/global-services'
      fullPath: '/admin/global-services'
      preLoaderRoute: typeof AuthenticatedAdminGlobalServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/access-codes': {
      id: '/_authenticated/admin/access-codes'
      path: '/access-codes'
      fullPath: '/admin/access-codes'
      preLoaderRoute: typeof AuthenticatedAdminAccessCodesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/sessions/$id/': {
      id: '/_authenticated/sessions/$id/'
      path: '/$id'
      fullPath: '/sessions/$id/'
      preLoaderRoute: typeof AuthenticatedSessionsIdIndexRouteImport
      parentRoute: typeof AuthenticatedSessionsRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/stripe': {
      id: '/api/public/hooks/stripe'
      path: '/api/public/hooks/stripe'
      fullPath: '/api/public/hooks/stripe'
      preLoaderRoute: typeof ApiPublicHooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/offer-tick': {
      id: '/api/public/hooks/offer-tick'
      path: '/api/public/hooks/offer-tick'
      fullPath: '/api/public/hooks/offer-tick'
      preLoaderRoute: typeof ApiPublicHooksOfferTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sessions/$id/play': {
      id: '/_authenticated/sessions/$id/play'
      path: '/$id/play'
      fullPath: '/sessions/$id/play'
      preLoaderRoute: typeof AuthenticatedSessionsIdPlayRouteImport
      parentRoute: typeof AuthenticatedSessionsRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAccessCodesRoute: typeof AuthenticatedAdminAccessCodesRoute
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRoute
  AuthenticatedAdminGlobalServicesRoute: typeof AuthenticatedAdminGlobalServicesRoute
  AuthenticatedAdminInvoicesRoute: typeof AuthenticatedAdminInvoicesRoute
  AuthenticatedAdminMarketingRoute: typeof AuthenticatedAdminMarketingRoute
  AuthenticatedAdminMetricsRoute: typeof AuthenticatedAdminMetricsRoute
  AuthenticatedAdminOnboardingRoute: typeof AuthenticatedAdminOnboardingRoute
  AuthenticatedAdminOrganisationsRoute: typeof AuthenticatedAdminOrganisationsRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPlatformAdminsRoute: typeof AuthenticatedAdminPlatformAdminsRoute
  AuthenticatedAdminPolicyTemplatesRoute: typeof AuthenticatedAdminPolicyTemplatesRoute
  AuthenticatedAdminPromoCodesRoute: typeof AuthenticatedAdminPromoCodesRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSalesRoute: typeof AuthenticatedAdminSalesRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminShippingRoute: typeof AuthenticatedAdminShippingRoute
  AuthenticatedAdminTeamRoute: typeof AuthenticatedAdminTeamRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAccessCodesRoute: AuthenticatedAdminAccessCodesRoute,
  AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRoute,
  AuthenticatedAdminGlobalServicesRoute: AuthenticatedAdminGlobalServicesRoute,
  AuthenticatedAdminInvoicesRoute: AuthenticatedAdminInvoicesRoute,
  AuthenticatedAdminMarketingRoute: AuthenticatedAdminMarketingRoute,
  AuthenticatedAdminMetricsRoute: AuthenticatedAdminMetricsRoute,
  AuthenticatedAdminOnboardingRoute: AuthenticatedAdminOnboardingRoute,
  AuthenticatedAdminOrganisationsRoute: AuthenticatedAdminOrganisationsRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminPlatformAdminsRoute: AuthenticatedAdminPlatformAdminsRoute,
  AuthenticatedAdminPolicyTemplatesRoute:
    AuthenticatedAdminPolicyTemplatesRoute,
  AuthenticatedAdminPromoCodesRoute: AuthenticatedAdminPromoCodesRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminSalesRoute: AuthenticatedAdminSalesRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminShippingRoute: AuthenticatedAdminShippingRoute,
  AuthenticatedAdminTeamRoute: AuthenticatedAdminTeamRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedSessionsRouteChildren {
  AuthenticatedSessionsNewRoute: typeof AuthenticatedSessionsNewRoute
  AuthenticatedSessionsIndexRoute: typeof AuthenticatedSessionsIndexRoute
  AuthenticatedSessionsIdPlayRoute: typeof AuthenticatedSessionsIdPlayRoute
  AuthenticatedSessionsIdIndexRoute: typeof AuthenticatedSessionsIdIndexRoute
}

const AuthenticatedSessionsRouteChildren: AuthenticatedSessionsRouteChildren = {
  AuthenticatedSessionsNewRoute: AuthenticatedSessionsNewRoute,
  AuthenticatedSessionsIndexRoute: AuthenticatedSessionsIndexRoute,
  AuthenticatedSessionsIdPlayRoute: AuthenticatedSessionsIdPlayRoute,
  AuthenticatedSessionsIdIndexRoute: AuthenticatedSessionsIdIndexRoute,
}

const AuthenticatedSessionsRouteWithChildren =
  AuthenticatedSessionsRoute._addFileChildren(
    AuthenticatedSessionsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAudioRoute: typeof AuthenticatedAudioRoute
  AuthenticatedAvailabilityRoute: typeof AuthenticatedAvailabilityRoute
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFrequenciesRoute: typeof AuthenticatedFrequenciesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedSessionsRoute: typeof AuthenticatedSessionsRouteWithChildren
  AuthenticatedBookingsIdRoute: typeof AuthenticatedBookingsIdRoute
  AuthenticatedBookingsIndexRoute: typeof AuthenticatedBookingsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAudioRoute: AuthenticatedAudioRoute,
  AuthenticatedAvailabilityRoute: AuthenticatedAvailabilityRoute,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFrequenciesRoute: AuthenticatedFrequenciesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedSessionsRoute: AuthenticatedSessionsRouteWithChildren,
  AuthenticatedBookingsIdRoute: AuthenticatedBookingsIdRoute,
  AuthenticatedBookingsIndexRoute: AuthenticatedBookingsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface HomeRouteChildren {
  HomeLoginRoute: typeof HomeLoginRoute
  HomeSignupRoute: typeof HomeSignupRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeLoginRoute: HomeLoginRoute,
  HomeSignupRoute: HomeSignupRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FlyerRoute: FlyerRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  OSlugRoute: OSlugRoute,
  OfferTokenRoute: OfferTokenRoute,
  OrderCancelledRoute: OrderCancelledRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  LovableEmailEventsRoute: LovableEmailEventsRoute,
  ApiPublicHooksOfferTickRoute: ApiPublicHooksOfferTickRoute,
  ApiPublicHooksStripeRoute: ApiPublicHooksStripeRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
